FROM centos

ENV S3_HELPER_PATH /srv/vod
ENV S3_HELPER_EXE_PATH $S3_HELPER_PATH/s3-helper
ENV S3_HELPER_CONFIG $S3_HELPER_PATH/config/s3-helper.yml
ENV S3_HELPER_AWS_CREDS_DIR /root

RUN rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm

RUN yum install -y kaltura-nginx


COPY ./dist/s3-helper $S3_HELPER_EXE_PATH
COPY ./dist/s3-helper /usr/local/sbin/s3-helper
COPY ./dist/default.yml $S3_HELPER_CONFIG
COPY ./dist/nginx.conf /etc/nginx/nginx.conf
COPY ./dist/entrypoint.sh  $S3_HELPER_PATH/entrypoint.sh


RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

STOPSIGNAL SIGTERM

WORKDIR $S3_HELPER_PATH

VOLUME ["${S3_HELPER_PATH}/config", "${S3_HELPER_AWS_CREDS_DIR}"]

CMD ["/srv/vod/entrypoint.sh"]



