FROM duhruh/golang:1.8-centos

ENV PACKAGE_PATH $GOPATH/src/github.com/crunchyroll/evs-s3helper

# application deps
RUN yum install -y git

# install glide
RUN curl https://glide.sh/get | sh

RUN go get github.com/derekparker/delve/cmd/dlv
RUN go get github.com/githubnemo/CompileDaemon

WORKDIR $PACKAGE_PATH

ADD glide.yaml $PACKAGE_PATH/glide.yaml
ADD glide.lock $PACKAGE_PATH/glide.lock

ADD . $PACKAGE_PATH

CMD ["go", "build", "-o", "dist/s3-helper", "s3-helper/s3-helper.go"]
