FROM centos

RUN rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm

RUN yum install -y kaltura-nginx

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]