FROM nytimes/nginx-vod-module

ENV S3_HELPER_PATH /srv/vod
ENV S3_HELPER_EXE_PATH $S3_HELPER_PATH/s3-helper
ENV S3_HELPER_CONFIG $S3_HELPER_PATH/config/s3-helper.yml
ENV S3_HELPER_AWS_CREDS_DIR /root

COPY ./dist/s3-helper $S3_HELPER_EXE_PATH
COPY ./dist/s3-helper /usr/local/sbin/s3-helper
COPY ./dist/default.yml $S3_HELPER_CONFIG
COPY ./dist/nginx.conf /usr/local/nginx/conf/nginx.conf
COPY ./dist/entrypoint.sh  $S3_HELPER_PATH/entrypoint.sh

WORKDIR $S3_HELPER_PATH

EXPOSE 80

VOLUME ["${S3_HELPER_PATH}/config", "${S3_HELPER_AWS_CREDS_DIR}"]

ENTRYPOINT []

CMD ["/srv/vod/entrypoint.sh"]